---
- name: Create a new VMs: 
  hosts: localhost 
  gather_facts: false
  vars_files: 
    creds.yml
  tasks: 
  - name: Clone multiple VMs from template
     local_action:
      module: vmware_guest
        hostname: "{{ vcenter_hostname }}" 
        username: "{{ vcenter_username }}" 
        password: "{{ vcenter_password }}" 
        folder: testansible 
        name: win19test01 
        state: poweredon guest_id: windows9Server64Guest 
        esxi_hostname: "{{ esxi_hostname }}" 
        disk: 
        - size_gb: 60
          type: thin
          datastore: DS01
       hardware:
         memory_mb: 4096
         num_cpus: 4
       wait_for_ip_address: false 
       with_items: "{{ servers }}"      
