---
- name: Create a VMs 
  hosts: 10.224.3.224
  gather_facts: false
  vars: 
    vcenter_hostname: is00esx016.iaas01.local
    username: administrator
    password: P@ssw0rd
    datastore: Temp Datastore
 
  tasks:
  - read_csv:
      path: /data.csv
    register: data

  tasks: 
  - name: Deploy multiple VMs from template
    vmware_guest: 
      hostname: "{{ vcenter_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no      
      template: "{{ data.Template }}"
      datastore: "{{ datastore }}"
      state: poweredon
    with_items: "{{ data.Name }}"
    loop: "{{ data.list }}"
    loop_control:
      loop_var: data
