---
- name: Create a VMs 
  hosts: localhost
  connection: local
  gather_facts: false
  vars: 
    vcenter_hostname: is00esx016.iaas01.local
    username: administrator
    password: P@ssw0rd
    datastore: Temp Datastore
 

  tasks: 
  - name: Deploy multiple VMs from template
    vmware_guest:
      datacenter: Management DC
      cluster: Management Cluster
      hostname: "{{ vcenter_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      name: "{{ data.Name }}"
      validate_certs: False      
      template: "{{ data.Template }}"
      datastore: "{{ datastore }}"
      state: poweredon
      wait_for_ip_address: no
    loop: "{{ data.list }}"
    loop_control:
      loop_var: data
      
