---
- name: Create a VM from a template 
  hosts: localhost

  gather_facts: false
  vars: 
    vcenter_hostname: is00esx016.iaas01.local
    username: administrator
    password: P@ssw0rd
    datastore: Temp Datastore
 
  tasks:
  - name: Read CSV file
    read_csv:
      path: /data.csv
    register: data

  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: testvm_2
      template: template_el7
      datacenter: "{{ datacenter_name }}"
      folder: /DC1/vm
      state: poweredon
      cluster: "{{ cluster_name }}"
      wait_for_ip_address: yes
