---
- name: Create a new VMs 
  hosts: 10.224.3.224
  gather_facts: false
  vars_files: 
    creds.yml
 
  tasks:
  - read_csv:
      path: /data.csv
    register: data

  - debug: 
      msg: "{{ data.Name }} ---- {{ data.Template }}"
    loop: "{{ data.list }}"
    loop_control:
      loop_var: data 
