---
- name: Create a new VMs 
  hosts: 10.224.3.224
  gather_facts: false
  vars_files: 
    creds.yml
 
  tasks:
  - read_csv:
      path: /data.csv
    register: data

  tasks: 
  - name: Deploy multiple VMs from template
    local_action:
      module: vmware_guest
      hostname: "{{ vcenter_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no      
      template: "{{ data.Template }}"
      datastore: "{{ datastore }}"
      state: poweredon
    with_items: "{{ data.Name }}"
