---
- name: Create a VMs 
  hosts: localhost
  connection: local
  gather_facts: false
  vars: 
    vcenter_hostname: is00esx016.iaas01.local
    username: administrator
    password: P@ssw0rd
    datastore: Temp Datastore
 
  tasks:
  - name: Read CSV file
    read_csv:
      path: /data.csv
    register: data

  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: 192.0.2.44
      username: administrator@vsphere.local
      password: vmware
      validate_certs: False
      name: testvm_2
      template: template_el7
      datacenter: DC1
      folder: /DC1/vm
      state: poweredon
      wait_for_ip_address: yes
      
