---
- name: Create a VM from a template 
  hosts: 10.224.3.223

  gather_facts: false
  vars: 
    vcenter_ip: 10.224.3.223
    username: administrator@iaas01.sso.local
    password: P@ssw0rd
    datastore: Temp Datastore
 
  tasks:
  - name: Read CSV file
    read_csv:
      path: /data.csv
    register: data

  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      name: testvm_2
      template: WinSvr2016Std-BaseImage
      datacenter: Management DC
      folder: 
      state: poweredon
      cluster: Management Cluster
      wait_for_ip_address: yes
