---
# This playbook prints a simple debug message
- name: Echo
  hosts: localhost
  become: yes
  become_user: root
  become_method: su
  gather_facts: false
  connection: local

  tasks:
  - name: Print debug message
    debug:
      msg: Hello, world!
